[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "x64dbg-automate"
include-before = [
	"cmake/msvc-static-runtime.cmake",
	"cmake/msvc-configurations.cmake",
]

[vcpkg]
version = "2025.01.13"
packages = ["cppzmq", "msgpack[boost]", "detours"]

[find-package.cppzmq]
required = true

[find-package.msgpack-cxx]
required = true

[find-package.Boost]
required = true

[fetch-content.x64dbg]
url = "https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2026-05-27_12-11.zip"
sha1 = "4f70bf300e79e0a88d59ab3bfe68d22daf003cea"
include-after = ["cmake/x64dbg.cmake"]

[template.plugin]
type = "shared"
add-function = "x64dbg_plugin"

[target.x64dbg-automate]
type = "plugin"
sources = [
    "src/*.cpp",
    "src/*.h",
    "src/plugin.rc",
]
cmake-before = """
find_path(DETOURS_INCLUDE_DIRS "detours/detours.h" REQUIRED)
find_library(DETOURS_LIBRARY detours REQUIRED)
add_library(detours_target STATIC IMPORTED)
set_target_properties(detours_target PROPERTIES
    IMPORTED_LOCATION "${DETOURS_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${DETOURS_INCLUDE_DIRS}"
)
"""
link-libraries = ["cppzmq", "msgpack-cxx", "detours_target"]
compile-features = ["cxx_std_20"]